# Generated by Django 5.2.10 on 2026-06-03 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='lunch', max_length=128)),
                ('info', models.CharField(default='lunch', max_length=129)),
                ('item', models.CharField(max_length=128)),
                ('variant', models.CharField(max_length=128)),
                ('method', models.TextField()),
                ('nutrients', models.TextField()),
                ('benefits', models.TextField()),
                ('hazards', models.TextField()),
            ],
        ),
    ]
