# Generated by Django 5.2.10 on 2026-06-03 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='info',
            field=models.CharField(default='lunch', max_length=130),
        ),
    ]
