# Generated by Django 5.2.10 on 2026-06-03 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_alter_food_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='info',
            field=models.TextField(),
        ),
    ]
