# Generated by Django 5.2.10 on 2026-08-08 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_food_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='info',
            field=models.CharField(default='lunch', max_length=129),
        ),
    ]
