# Generated by Django 5.2.10 on 2026-06-02 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('symptoms', models.TextField()),
                ('medicines', models.TextField()),
                ('f2avoid', models.TextField(default='nkj')),
            ],
        ),
    ]
