# Generated by Django 5.2.10 on 2026-06-03 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_disease'),
    ]

    operations = [
        migrations.AddField(
            model_name='disease',
            name='info',
            field=models.TextField(default='lunch'),
        ),
    ]
