# Generated by Django 5.2.10 on 2026-06-05 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_disease_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='disease',
            name='type',
            field=models.CharField(default='lunch', max_length=129),
        ),
    ]
