# Generated by Django 5.2.10 on 2026-06-06 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_disease_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disease',
            name='name',
            field=models.TextField(default='lunch'),
        ),
    ]
